### ISSUE TITLE
dataset access

### ISSUE THREAD

**Issue by junqiangchen** [XiaoweiXu/ImageCAS-A-Large-Scale-Dataset-and-Benchmark-for-Coronary-Artery-Segmentation-based-on-CT#1]
Hi，xiaowei
I have sent the dataset download request via email xiao.wei.xu@foxmail.com.
Please check and confirm, looking forward to your reply
thank you!!
chenjunqiang

**Comment by simi-chen** [comment]
请问你获得了数据集了吗

**Comment by lidh15** [comment]
请问你获得了数据集了吗？是否可以二次分发？

**Comment by junqiangchen** [comment]
> 请问您获得了数据集了吗？是否可以二次分发？

https://www.kaggle.com/datasets/xiaoweixumedicalai/imagecas

**Comment by junqiangchen** [comment]
> 请问您获得数据集了吗

https://www.kaggle.com/datasets/xiaoweixumedicalai/imagecas
